backend: fixture

fixture:
  path: fixtures/sample-calendar.json

cybozu-html:
  base_url: https://example.cybozu.com/o/ag.cgi
  office_login_url: https://example.cybozu.com/login
  office_login_post_url: https://example.cybozu.com/api/auth/redirect.do
  basic_username_env: CBZCAL_BASIC_USER
  basic_password_env: CBZCAL_BASIC_PASS
  # basic_username: temporary-basic-user
  # basic_password: temporary-basic-pass
  office_username_env: CBZCAL_OFFICE_USER
  office_password_env: CBZCAL_OFFICE_PASS
  # office_username: temporary-office-user
  # office_password: temporary-office-pass
  user_agent: cbzcal/0.1.0
